site_name: matt
site_description: matt note
site_author: matt
site_url: https://imatt.top
strict: false

# Repository
repo_name: 'imattdu/imattdu.github.io'
repo_url: 'https://github.com/imattdu/imattdu.github.io'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Matt Note'

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.ico
  palette:
    primary: white  
  features:
    - navigation.instant
    - navigation.tabs
    # 自动隐藏
    - header.autohide
    # 返回顶部
    - navigation.top
      
plugins:
  - search

extra:
  disqus: 'imattdu'
  generator: false
  social:
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/   
# 内容选项卡
markdown_extensions:
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - 基础:
    - Getting Started: index.md
    - go: 00go/0base/0安装.md
    - tool: 09tool/app.md
    - 格式手册: intro/format.md
    - F.A.Q.: intro/faq.md
    - 用 Docker 部署 OI Wiki: intro/docker-deploy.md
    - 镜像站列表: intro/mirrors.md
    - 致谢: intro/thanks.md
  - 算法:
    - 基础:
      - 基础算法: 10algorithm/base/0基础算法.md
      - 数据结构: 10algorithm/base/1数据结构.md
      - 搜索与图论: 10algorithm/base/2搜索与图论.md
      - 数学: 10algorithm/base/3数学.md


