site_name: Matt
site_description: matt note
site_author: matt
site_url: https://imatt.top
strict: false

# Repository
repo_name: 'imattdu/imattdu.github.io'
repo_url: 'https://github.com/imattdu/imattdu.github.io'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Matt Note'

theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  logo: images/matt.png
  favicon: images/favicon.ico
  palette:
    primary: white  
  features:
    # 实时加载
    - navigation.instant
    # tabs
    - navigation.tabs
    # 自动隐藏
    # - header.autohide
    # 返回顶部
    - navigation.top
    # 代码注释
    - content.code.annotate
    - search.highlight
    - search.suggest
    # 搜索共享
    - search.share
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'


extra:
  disqus: 'imattdu'
  generator: false
  social:
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/   
# 内容选项卡
markdown_extensions:
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # 代码高亮配置
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # 自定义图标
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - 基础:
    - Getting Started: index.md
    - go:
      - base:
        - 安装: 00go/0base/0安装.md
        - 基础: 00go/0base/1基础.md
        - 常用数据结构: 00go/0base/2常用数据结构.md
        - 函数: 00go/0base/3函数.md
    - tool:
      - mac:
        - 基本使用: 09tool/1mac/0基本使用.md
        - 常用软件: 09tool/1mac/1常用软件.md
        - iterm2美化: 09tool/1mac/2iterm2美化.md
  - 算法:
    - 基础:
      - 基础算法: 10algorithm/base/0基础算法.md
      - 数据结构: 10algorithm/base/1数据结构.md
      - 搜索与图论: 10algorithm/base/2搜索与图论.md
      - 数学: 10algorithm/base/3数学.md
  - web:
    - gin:
      - base: 23frame/gin/base.md
  - mw:
    - kafka:
      - 概述: 33mq/0kafka/0概述.md
      - 安装: 33mq/0kafka/1安装.md
    - zookeeper:
      - zookeeper学习: 34mw/zookeeper/zookeeper学习.md
    - es:
      - 基础: 34mw/es/es基础.md    


extra_css:
  - stylesheets/extra.css

